# Generated by Django 2.2.2 on 2019-07-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190714_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(default='Zero, zip, nada (only true fans will get this!!!)', max_length=500),
        ),
    ]
