# Generated by Django 2.2.2 on 2019-07-14 11:08

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190714_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(default=projects.models.default_str, max_length=500),
        ),
    ]
